<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    /** @use HasFactory<\Database\Factories\FfgModelFactory> */
    use HasFactory;

    protected $table = 'InvMaster';
    public $timestamps = false;
    protected $hidden = ['TimeStamp'];

    // // Specify the primary key column name
    // protected $primaryKey = 'productID';

    // protected $fillable = [
    //     'StockCode',
    //     'Description',
    //     'Brand',
    //     'StockUom',
    //     'priceWithVat',
    //     'time_stamp',
    //     'buyingAccounts',
    // ];

    protected $fillable = [
        'StockCode',
        'Description',
        'LongDesc',
        'AlternateKey1',
        // 'AlternateKey2',
        // 'EccUser',
        'StockUom',
        'AlternateUom',
        'OtherUom',
        'ConvFactAltUom',
        'ConvMulDiv',
        'ConvFactOthUom',
        'MulDiv',
        'Mass',
        'Volume',
        'Decimals',
        // 'PriceCategory',
        // 'PriceMethod',
        'Supplier',
        // 'CycleCount',
        'ProductClass',
        'TaxCode',
        // 'OtherTaxCode',
        // 'ListPriceCode',
        'SerialMethod',
        'InterfaceFlag',
        'KitType',
        'LowLevelCode',
        // 'Buyer',
        // 'Planner',
        'TraceableType',
        'MpsFlag',
        'BulkIssueFlag',
        'AbcClass',
        'LeadTime',
        'StockMovementReq',
        'ClearingFlag',
        // 'SupercessionDate',
        'AbcAnalysisReq',
        'AbcCostingReq',
        'CostUom',
        'MinPricePct',
        'LabourCost',
        'MaterialCost',
        'FixOverhead',
        'VariableOverhead',
        'PartCategory',
        // 'DrawOfficeNum',
        'WarehouseToUse',
        'BuyingRule',
        'SpecificGravity',
        'ImplosionNum',
        'Ebq',
        'ComponentCount',
        'FixTimePeriod',
        'PanSize',
        'DockToStock',
        'OutputMassFlag',
        'ShelfLife',
        // 'Version',
        // 'Release',
        'DemandTimeFence',
        'MakeToOrderFlag',
        'ManufLeadTime',
        'GrossReqRule',
        'PercentageYield',
        'AbcPreProd',
        'AbcManufacturing',
        'AbcSales',
        'AbcCumPreProd',
        'AbcCumManuf',
        // 'WipCtlGlCode',
        // 'ResourceCode',
        'GstTaxCode',
        'PrcInclGst',
        'SerEntryAtSale',
        // 'StpSelection',
        // 'UserField1',
        'UserField2',
        'UserField3',
        'UserField4',
        // 'UserField5',
        // 'TariffCode',
        'SupplementaryUnit',
        'EbqPan',
        // 'StdLandedCost',
        'LctRequired',
        'StdLctRoute',
        'IssMultLotsFlag',
        'InclInStrValid',
        'StdLabCostsBill',
        // 'PhantomIfComp',
        // 'CountryOfOrigin',
        // 'StockOnHold',
        // 'StockOnHoldReason',
        'EccFlag',
        'StockAndAltUm',
        'AltUnitChar',
        // 'JobsOnHold',
        // 'JobHoldAllocs',
        // 'PurchOnHold',
        // 'SalesOnHold',
        // 'MaintOnHold',
        'BatchBill',
        // 'BlanketPoExists',
        // 'CallOffBpoExists',
        // 'DistWarehouseToUse',
        // 'JobClassification',
        'SubContractCost',
        'DateStkAdded',
        // 'InspectionFlag',
        // 'SerialPrefix',
        // 'SerialSuffix',
        // 'ReturnableItem',
        // 'ProductGroup',
        // 'PriceType',
        // 'Basis',
        // 'ManualCostFlag',
        // 'ManufactureUom',
        'ConvFactMuM',
        // 'ManMulDiv',
        'LookAheadWin',
        'LoadingFactor',
        // 'SupplUnitCode',
        // 'StorageSecurity',
        // 'StorageHazard',
        // 'StorageCondition',
        'ProductShelfLife',
        'InternalShelfLife',
        // 'AltMethodFlag',
        // 'AltSisoFlag',
        // 'AltReductionFlag',
        // 'WithTaxExpenseType',
        // 'UsesPrefSupplier',
        // 'PrdRecallFlag',
        // 'OnHoldReason',
        'SpecificGravity6',
        'SuppUnitFactor',
        // 'SuppUnitsMulDiv',
        // 'QmInspectionReq',
    ];
}
